import { existsSync, readFileSync, readdirSync, statSync } from 'node:fs';
import assert from 'node:assert/strict';

function readSourceTree(pathUrl) {
  const path = pathUrl instanceof URL ? pathUrl : new URL(pathUrl, import.meta.url);
  const stat = statSync(path);
  if (stat.isFile()) return readFileSync(path, 'utf8');
  return readdirSync(path)
    .filter((name) => !name.endsWith('.css'))
    .map((name) => readSourceTree(new URL(`${name}${statSync(new URL(name, path)).isDirectory() ? '/' : ''}`, path)))
    .join('\n');
}

function listSourceFiles(pathUrl) {
  const path = pathUrl instanceof URL ? pathUrl : new URL(pathUrl, import.meta.url);
  const stat = statSync(path);
  if (stat.isFile()) return [path.pathname];
  return readdirSync(path).flatMap((name) => listSourceFiles(new URL(`${name}${statSync(new URL(name, path)).isDirectory() ? '/' : ''}`, path)));
}

const sourceFiles = listSourceFiles('../src/');
const packageJson = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
assert.deepEqual(sourceFiles.filter((path) => /\.[cm]?jsx?$/.test(path)), []);
const app = readSourceTree('../src/');
const main = readFileSync(new URL('../src/main.tsx', import.meta.url), 'utf8');
const cssEntry = readFileSync(new URL('../src/styles.css', import.meta.url), 'utf8');
const cssPartialsDir = new URL('../src/styles/', import.meta.url);
function readStylePartials(pathUrl) {
  if (!existsSync(pathUrl)) return '';
  return readdirSync(pathUrl)
    .sort()
    .map((name) => {
      const child = new URL(`${name}${statSync(new URL(name, pathUrl)).isDirectory() ? '/' : ''}`, pathUrl);
      if (statSync(child).isDirectory()) return readStylePartials(child);
      return name.endsWith('.scss') ? readFileSync(child, 'utf8') : '';
    })
    .filter(Boolean)
    .join('\n');
}
const cssPartials = readStylePartials(cssPartialsDir);
const css = `${cssEntry}\n${cssPartials}`;
const sassFunctions = readFileSync(new URL('../src/styles/abstracts/_functions.scss', import.meta.url), 'utf8');
const sassMixins = readFileSync(new URL('../src/styles/abstracts/_mixins.scss', import.meta.url), 'utf8');
const conversationsView = readFileSync(new URL('../src/views/Conversations/index.tsx', import.meta.url), 'utf8');
const homeView = readFileSync(new URL('../src/views/Home/index.tsx', import.meta.url), 'utf8');
const appShellSource = readFileSync(new URL('../src/components/organisms/AppShell.tsx', import.meta.url), 'utf8');
const genreSource = readFileSync(new URL('../src/constants/domain.ts', import.meta.url), 'utf8');
const inputPrimitive = readFileSync(new URL('../src/components/atoms/input.tsx', import.meta.url), 'utf8');
const selectPrimitive = readFileSync(new URL('../src/components/atoms/select.tsx', import.meta.url), 'utf8');
const textareaPrimitive = readFileSync(new URL('../src/components/atoms/textarea.tsx', import.meta.url), 'utf8');
const buttonPrimitive = readFileSync(new URL('../src/components/atoms/button.tsx', import.meta.url), 'utf8');
const commandBlockSource = readFileSync(new URL('../src/components/molecules/CommandBlockRenderer.tsx', import.meta.url), 'utf8');
const uiStoreSource = readFileSync(new URL('../src/stores/uiStore.ts', import.meta.url), 'utf8');
const settingsViewSource = readFileSync(new URL('../src/views/Settings/index.tsx', import.meta.url), 'utf8');
const modelSettingsViewSource = readFileSync(new URL('../src/views/ModelSettings/index.tsx', import.meta.url), 'utf8');
const operationsViewSource = readFileSync(new URL('../src/views/Operations/index.tsx', import.meta.url), 'utf8');
const navigationDrawerSource = readFileSync(new URL('../src/components/organisms/Drawer.tsx', import.meta.url), 'utf8');
const drawerSource = readFileSync(new URL('../src/components/organisms/ConversationInfoDrawer.tsx', import.meta.url), 'utf8');
const appRootSource = readFileSync(new URL('../src/app/App.tsx', import.meta.url), 'utf8');
const generationJobEventsSource = readFileSync(new URL('../src/api/generationJobEvents.ts', import.meta.url), 'utf8');
const viteConfig = readFileSync(new URL('../vite.config.js', import.meta.url), 'utf8');
const removedFrontendManagementFiles = [
  '../src/components/organisms/LexiconForm.tsx',
  '../src/components/organisms/SystemPromptForm.tsx',
  '../src/views/Lexicon/index.tsx',
  '../src/views/LexiconDetail/index.tsx',
  '../src/views/SystemPrompts/index.tsx',
  '../src/views/SystemPromptDetail/index.tsx',
];
assert.deepEqual(removedFrontendManagementFiles.filter((path) => existsSync(new URL(path, import.meta.url))), []);

assert.match(main, /import \{ App \} from '\.\/app\/App'/);
assert.match(main, /import \{ AppProviders \} from '\.\/app\/AppProviders'/);
assert.match(main, /const root = document\.getElementById\('root'\)/);
assert.match(main, /if \(!root\) throw new Error\('Root element not found'\)/);
assert.match(main, /<AppProviders><App \/><\/AppProviders>/);
assert.match(cssEntry, /@import "\.\/styles\/base\/_typography\.scss"/);
assert.match(cssEntry, /@import "\.\/styles\/pages\/_chat\.scss"/);
assert.match(cssEntry, /@import "\.\/styles\/themes\/_dark\.scss"/);
assert.match(sassFunctions, /@function rem/);
assert.match(sassMixins, /@mixin truncate-one-line/);
assert.match(sassMixins, /@mixin round-control/);
assert.doesNotMatch(main, /function App\(/);
assert.match(app, /export function App\(/);
assert.match(app, /QueryClientProvider/);
assert.match(app, /export type AppProvidersProps/);
assert.match(app, /export function AppProviders\(\{ children \}: AppProvidersProps\)/);
assert.match(app, /new QueryClient/);
assert.match(app, /useAppDerivedData/);
assert.match(app, /export type AppDerivedDataOptions/);
assert.match(app, /export type AppDerivedDataState/);
assert.match(app, /export function useAppDerivedData\([\s\S]*\): AppDerivedDataState/);
assert.match(app, /function normalizeDerivedPage\(/);
assert.match(app, /export type BootstrapResourcesState/);
assert.match(app, /export function useBootstrapResources\(\): BootstrapResourcesState/);
assert.match(app, /useBootstrapSync/);
assert.match(app, /export type BootstrapSyncOptions/);
assert.match(app, /export function useBootstrapSync\(\{[\s\S]*bootstrap/);
assert.match(app, /useRouteResourceSync/);
assert.match(app, /export type RouteResourceSyncOptions/);
assert.match(app, /function normalizeCharacterDraft\(character: Entity\)/);
assert.match(app, /useQuery\(/);
assert.match(app, /queryKeys/);
assert.match(app, /characterApi/);
assert.match(app, /export type CharacterMutationsState/);
assert.match(app, /export function useCharacterMutations\(\): CharacterMutationsState/);
assert.match(app, /export type GenreModeOption/);
assert.match(app, /export type RuntimeSettingDefaults/);
assert.match(app, /export const API_BASE: string/);
assert.match(app, /export const DEFAULT_RUNTIME_SETTING: RuntimeSettingDefaults/);
assert.match(app, /export type ApiOptions/);
assert.match(app, /export async function api<T = unknown>\(path: string, options: ApiOptions = \{\}\): Promise<T \| null>/);
assert.match(app, /type SavePayload = \{ id\?: string \| null; payload: unknown \}/);
assert.match(app, /generateMessageTts: useMutation/);
assert.doesNotMatch(app, /api\(`\/messages\/\$\{message\.id\}\/tts`/);
assert.match(app, /createRouter/);
assert.match(app, /export type RouteName/);
assert.match(app, /export function createAppRouter\(\): Router<any, any/);
assert.match(app, /routeNames/);
assert.match(app, /RoutePage/);
assert.match(app, /export type LegacyRoute/);
assert.match(app, /export function parseRoute\(pathname: string = window\.location\.pathname\): LegacyRoute/);
assert.match(app, /export function paginate<T>/);
assert.match(app, /export function normalizeGenreMode\(value: unknown\): string/);
assert.match(app, /export function assetUrlFor\(url: unknown\): string/);
assert.match(app, /export function parseInputMarkup\(raw: unknown\): ParsedInputMarkup/);
assert.match(app, /export type CharacterDraftInput/);
assert.match(app, /export function normalizeCharacterForApi\(character: CharacterDraftInput\)/);
assert.doesNotMatch(app, /export function serializeRoomTemplate\(template: RoomTemplateDraft\): string/);
assert.match(app, /views\/Home/);
assert.match(app, /views\/Characters/);
assert.match(app, /views\/Conversations/);
assert.match(app, /views\/Settings/);
assert.match(app, /views\/ConversationDetail/);
assert.match(app, /views\/Presets/);
assert.match(app, /views\/PresetDetail/);
assert.match(app, /export type PresetDetailViewProps/);
assert.match(app, /export function PresetDetailView\(/);
assert.doesNotMatch(app, /views\/Lexicon|LexiconDetailView|views\/SystemPrompt|SystemPromptDetailView/);
assert.match(app, /views\/ChatCommands/);
assert.match(app, /title: '커맨드'/);
assert.match(app, /label: '커맨드'/);
assert.match(app, /label: '설정'/);
assert.doesNotMatch(app, /label: '운영'/);
assert.doesNotMatch(app, /label: '커맨드 관리'/);
assert.doesNotMatch(app, /label: 'UI\/UX'/);
assert.match(app, /views\/ModelSettings/);
assert.doesNotMatch(app, /views\/Operations|views\/Uiux/);
assert.match(app, /modelSettings: '\/model-settings'/);
assert.doesNotMatch(app, /operations: '\/operations'|uiux: '\/uiux'/);
assert.match(settingsViewSource, /path: '\/model-settings', label: '모델 설정'/);
assert.match(settingsViewSource, /path: '\/presets', label: '프리셋'/);
assert.match(settingsViewSource, /SettingsNavItem/);
assert.doesNotMatch(settingsViewSource, /RuntimeSettingsPanel|\/lexicon|단어집|\/system-prompts|시스템 프롬프트|\/uiux|UI\/UX 가이드/);
assert.match(modelSettingsViewSource, /RuntimeSettingsPanel/);
assert.match(modelSettingsViewSource, /title=\{t\('모델 설정'\)\}/);
assert.match(modelSettingsViewSource, /data-settings-section="runtime"/);
assert.match(modelSettingsViewSource, /data-settings-section="providers"/);
assert.match(modelSettingsViewSource, /data-settings-section="models"/);
assert.match(app, /export type ProviderType = [^;]*'xai'/);
assert.match(app, /model_family: [^;]*'grok'/);
assert.match(modelSettingsViewSource, /type: 'xai', label: 'xAI Grok'/);
assert.match(modelSettingsViewSource, /모델 불러오기/);
assert.match(modelSettingsViewSource, /toggleModelOption/);
assert.match(operationsViewSource, /\['\/uiux', 'UI\/UX 가이드'/);
assert.doesNotMatch(operationsViewSource, /\/system-prompts|시스템 프롬프트/);
assert.match(app, /chatCommands/);
assert.match(app, /clearActiveCommand/);
assert.match(app, /active-command\/clear/);
assert.match(app, /활성 커맨드 해제/);
assert.match(app, /chat-header-actions/);
assert.match(app, /export type ChatCommandItem/);
assert.match(app, /export function ChatCommandsView/);
assert.match(app, /chatCommands: \(\) => api\('\/chat-commands'\)/);
assert.doesNotMatch(app, /chatCommands: \(\) => api\('\/chat-commands\?include_disabled=true'\)/);
assert.match(app, /saveChatCommand/);
assert.match(app, /deleteChatCommand/);
assert.match(app, /active_command_id/);
assert.match(app, /active_command_ids/);
assert.match(app, /active-command-badge/);
assert.match(app, /active-command\/\$\{commandId\}\/clear/);
assert.match(app, /command-autocomplete/);
assert.match(app, /command-autocomplete-backdrop/);
assert.match(app, /slice\(0, 30\)/);
assert.match(css, /\.command-autocomplete-backdrop/);
assert.match(css, /z-index: 88/);
assert.match(css, /display: none/);
assert.match(css, /min-height: min\(22vh, 180px\)/);
assert.match(css, /padding: 10px 10px 22px/);
assert.match(css, /overflow-y: auto/);
assert.match(css, /overscroll-behavior: contain/);
assert.match(app, /commandAutocompleteActive/);
assert.doesNotMatch(app, /!off/);
assert.doesNotMatch(app, /<CardTitle>커맨드 관리<\/CardTitle>/);
assert.match(app, /커맨드 검색/);
assert.match(app, /<span>\{label\}<\/span>/);
assert.match(app, /<strong>\{command\.display_name \|\| command\.name\}<\/strong>/);
assert.doesNotMatch(app, /<span>!\{label\} 활성<\/span>|<strong>!\{command\.name\}<\/strong>|`!\$\{chatCommandDraft\.name\} 수정`/);
assert.match(app, /상세 편집 design-system primitive marker/);
assert.doesNotMatch(app, /<CardTitle>\{route\.page === 'presetNew'/);
assert.doesNotMatch(app, /views\/RelationshipMap|RelationshipMapView|relationshipMap|relationship-map/);
assert.doesNotMatch(app, /views\/DataCleanup|DataCleanupView|dataCleanup|data-cleanup/);
assert.doesNotMatch(app, /opsApi/);
assert.match(app, /views\/ConversationEdit/);
assert.match(app, /export type ConversationEditViewProps/);
assert.match(app, /export function ConversationEditView\(/);
assert.match(app, /export type ConversationDetailViewProps/);
assert.match(app, /export function ConversationDetailView/);
assert.match(app, /useConversationComposer/);
assert.match(app, /export type ConversationComposerOptions/);
assert.match(app, /export type ConversationComposerState/);
assert.match(app, /export function useConversationComposer\(\{ compose, composerTextareaRef, sendConversationMessage \}: ConversationComposerOptions\): ConversationComposerState/);
assert.match(app, /useConversationMutations/);
assert.match(app, /export type ConversationMutationsState/);
assert.match(app, /export function useConversationMutations\(\): ConversationMutationsState/);
assert.match(app, /updateMessage: \(id: Id, messageId: Id, payload: Payload\) => api\(`\/conversations\/\$\{id\}\/messages\/\$\{messageId\}`/);
assert.match(app, /updateSceneSummary: \(id: Id, payload: Payload\) => api\(`\/conversations\/\$\{id\}\/scene-summary`/);
assert.match(app, /버블 대사 수정/);
assert.match(app, /버블 행동 수정/);
assert.match(app, /버블 속마음 수정/);
assert.match(app, /수정 저장/);
assert.match(drawerSource, /Story Arc 수정/);
assert.match(drawerSource, /expectedRevision/);
assert.match(drawerSource, /Arc 저장/);
assert.match(drawerSource, /formatStoryArcLimit\(sceneSummaryDraft\.length, locale\)/);
assert.doesNotMatch(drawerSource, /<p className="context-muted">revision/);
assert.match(css, /\.context-drawer \{[^}]*z-index: 90/);
assert.match(css, /\.drawer-tab-content \{[^}]*padding-bottom: calc\(72px \+ env\(safe-area-inset-bottom, 0px\)\)/);
assert.match(app, /useConversationAutoScroll/);
assert.match(app, /export type ConversationAutoScrollOptions/);
assert.match(app, /export function useConversationAutoScroll\(\{[\s\S]*selectedConversationId/);
assert.match(app, /usePreviewModals/);
assert.match(app, /export type PreviewModalState/);
assert.match(app, /export function usePreviewModals\(\): PreviewModalState/);
assert.match(app, /export function useLegacyNavigation\(\): LegacyNavigationState/);
assert.match(app, /export const queryClient: QueryClient/);
assert.match(app, /useSettingsMutations/);
assert.match(app, /export type SettingsMutationsState/);
assert.match(app, /export function useSettingsMutations\(\): SettingsMutationsState/);
assert.match(app, /useRuntimeDefaultSetting/);
assert.match(app, /export type RuntimeDefaultSettingOptions/);
assert.match(app, /export type RuntimeDefaultSettingState/);
assert.match(app, /export function useRuntimeDefaultSetting\(\{ settingsMutations, setBusy, setStatus \}: RuntimeDefaultSettingOptions\): RuntimeDefaultSettingState/);
assert.doesNotMatch(app, /saveLexiconEntry|deleteLexiconEntry|saveSystemPrompt|deleteSystemPrompt/);
assert.match(app, /useMutation\(/);
assert.match(app, /appRouter\.navigate/);
assert.match(app, /toRouterPath/);
assert.match(viteConfig, /@tailwindcss\/vite/);
assert.match(app, /lib\/utils/);
assert.match(app, /export function cn\(\.\.\.inputs: ClassValue\[\]\)/);
assert.match(app, /@radix-ui\/react-slot/);
assert.match(app, /export function Button\(/);
assert.match(app, /design-system product button hierarchy/);
assert.match(app, /mediaSquare/);
assert.match(app, /mediaSquare: 'aspect-square/);
assert.match(app, /variant === 'mediaSquare' \? 'rounded-none' : 'rounded-2xl'/);
assert.match(buttonPrimitive, /default: 'border border-primary bg-primary text-primary-foreground/);
assert.doesNotMatch(buttonPrimitive, /!bg|!text|!border/);
assert.doesNotMatch(buttonPrimitive, /shadow-blue-950/);
assert.match(inputPrimitive, /text-sm/);
assert.doesNotMatch(inputPrimitive, /text-base/);
assert.match(selectPrimitive, /text-sm/);
assert.doesNotMatch(selectPrimitive, /text-base/);
assert.match(textareaPrimitive, /text-sm/);
assert.doesNotMatch(textareaPrimitive, /text-base/);
assert.match(css, /--color-primary: var\(--primary\)/);
assert.match(css, /--color-card-foreground: var\(--foreground\)/);
assert.match(css, /--bg: #f5f5f6/);
assert.match(css, /--primary: #e45161/);
assert.match(css, /--accent: #e45161/);
assert.match(css, /--accent-2: #5975df/);
assert.match(css, /--surface-glow: transparent/);
assert.match(css, /color-scheme: light/);
assert.doesNotMatch(css, /--color-primary: #2563eb/);
assert.doesNotMatch(css, /--accent: #2563eb/);
assert.match(app, /default: 'border border-primary bg-primary/);
assert.match(app, /destructive: 'border border-danger bg-danger text-white/);
assert.match(css, /\.form-action-row > button \{ flex: 1 1 0/);
assert.doesNotMatch(css, /\.bubble-dialogue|\.bubble\.right \.bubble-dialogue/);
assert.match(app, /m-0 whitespace-pre-wrap text-\[14px\] font-\[430\] leading-\[1\.45\] text-inherit/);
assert.match(css, /@custom-variant dark \(&:where\(\.theme-dark, \.theme-dark \*\)\)/);
assert.doesNotMatch(commandBlockSource, /command-vote-track|command-vote-fill|bg-muted/);
assert.match(commandBlockSource, /bg-\[linear-gradient\(90deg,#ffe8ec,#fff4f6\)\]/);
assert.match(commandBlockSource, /dark:bg-\[linear-gradient\(90deg,rgba\(98,111,134,\.34\),rgba\(98,111,134,\.34\)\)\]/);
assert.match(commandBlockSource, /bg-\[linear-gradient\(90deg,#ff9aaa_0%,#f05a68_48%,#b91c3a_100%\)\]/);
assert.match(commandBlockSource, /dark:bg-\[linear-gradient\(90deg,color-mix\(in_srgb,var\(--success\)_88%,#fff\),color-mix\(in_srgb,var\(--accent-2\)_76%,#fff\)\)\]/);
assert.doesNotMatch(css, /\.command-vote-track|\.command-vote-fill|\.bg-amber-500\\\\\/10|\.border-amber-500\\\\\/40|\.text-amber-100/);
assert.match(app, /export function Card\(/);
assert.match(app, /Flat secondary surface/);
assert.match(app, /data-design-system="flat card surface"/);
assert.match(app, /export function Select\(/);
assert.match(css, /font-family: 'Pretendard'/);
assert.match(css, /\.text-display/);
assert.match(css, /\.text-lg/);
assert.match(css, /\.text-md/);
assert.match(css, /\.text-sm/);
assert.match(app, /function BackendHealth/);
assert.match(app, /server-health/);
assert.doesNotMatch(appShellSource, /API_BASE|API \{/);
assert.doesNotMatch(appShellSource, /title=\{API_BASE\}/);
assert.doesNotMatch(app, /Backend online|Backend offline|>online<|>offline</);
assert.match(app, /Menu/);
assert.match(app, /MessageSquare/);
assert.doesNotMatch(app, /운영 허브야|보여줘|보여주는 중이야|설정 없는 방에 적용돼/);
assert.doesNotMatch(app, /수 있어|볼 수 있어|늘릴 수 있어|이어져|적어줘|없어\.|없어<|없어'/);
assert.doesNotMatch(app, /만들어\.|캐릭터가 이어가|프사로|끄기|켜기|가능해요|했어요|해요|돼요|얘기해봐/);
assert.match(app, /export function Switch\(/);
assert.match(app, /export function Slider\(/);
assert.match(css, /@import "tailwindcss"/);
assert.match(css, /@theme/);
assert.match(viteConfig, /node_modules\/@tanstack/);
assert.match(app, /export type HomeViewProps/);
assert.match(app, /export function HomeView/);
assert.match(app, /대화방 생성 world-select-only marker/);
assert.doesNotMatch(app, /<CardTitle>대화방 만들기<\/CardTitle>/);
assert.match(app, /export type CharactersListViewProps/);
assert.match(app, /export function CharactersListView/);
assert.match(app, /export type ConversationsListViewProps/);
assert.match(app, /export function ConversationsListView/);
assert.match(app, /export type ConversationEditViewProps/);
assert.match(app, /export function ConversationEditView/);
assert.match(app, /대화방 수정 world-select-only marker/);
assert.doesNotMatch(app, /<CardTitle>대화방 수정<\/CardTitle>/);
assert.match(app, /uniform resource cards/);
assert.match(app, /uniform resource cards and corner actions/);
assert.doesNotMatch(app, /<CardTitle>캐릭터 목록<\/CardTitle>/);
assert.doesNotMatch(app, /<CardTitle>대화방 목록<\/CardTitle>/);
assert.match(app, /export type SettingsViewProps/);
assert.match(app, /export function SettingsView/);
assert.match(app, /export type PresetsViewProps/);
assert.match(app, /export function PresetsView/);
assert.match(app, /data-page="presets-list"/);
assert.doesNotMatch(app, /<CardTitle>프리셋<\/CardTitle>/);
assert.match(app, /components\/molecules/);
assert.match(app, /export type FieldProps/);
assert.match(app, /className\?: string/);
assert.match(app, /export function Field\(\{ label, children, className \}: FieldProps\)/);
assert.match(app, /export type PagerProps/);
assert.match(app, /export function Pager\(\{ page, total, onPage \}: PagerProps\)/);
assert.match(app, /export type TextareaWithExpandProps/);
assert.match(app, /export function TextareaWithExpand\([\s\S]*TextareaWithExpandProps\)/);
assert.match(app, /textarea 확장 design-system primitive marker/);
assert.match(app, /compression_interval_options/);
assert.match(app, /2턴마다 · 강한 기억 유지/);
assert.match(app, /새 방\/관계 초반처럼 첫 상황과 말맛을 자주 고정/);
assert.match(app, /compressionIntervalOptions\(value\)\.map/);
assert.doesNotMatch(app, /<option value="3">3턴마다 · 자주\/안전<\/option><option value="5">5턴마다 · 기본 추천/);
assert.doesNotMatch(app, /첫상황·첫대사가 있는 새 방은 초반 말맛 보존을 위해 2턴 압축으로 자동 시작됩니다/);
assert.doesNotMatch(app, /초반 기억 강화/);
assert.doesNotMatch(app, /data-modernized="room-flavor-compression-cadence-hint design-system primitive marker"/);
assert.match(app, /runtime 설정 design-system primitive marker/);
assert.match(app, /data-modernized="genre-mode-select"/);
assert.match(app, /프리셋 폼 design-system primitive marker/);
assert.doesNotMatch(app, /룸 템플릿 design-system primitive marker/);
assert.match(app, /utils\/assets/);
assert.match(app, /utils\/pagination/);
assert.doesNotMatch(app, /utils\/roomTemplates/);
assert.match(app, /utils\/text/);
assert.match(app, /components\/organisms/);
assert.match(app, /export type AppShellProps/);
assert.match(app, /headerActions\?: ReactNode/);
assert.match(app, /export function AppShell\(\{ route, backendOnline, drawerOpen, setDrawerOpen, navigate, children, overlays, headerActions \}: AppShellProps\)/);
assert.match(app, /aria-label=\{t\('페이지 액션'\)\}/);
assert.match(app, /justify-end/);
assert.doesNotMatch(app, /flex-row-reverse/);
assert.doesNotMatch(app, /새로고침/);
assert.match(app, /drawer-footer/);
assert.match(app, /drawer-status-controls/);
assert.doesNotMatch(app, /drawer-user-profile|drawer-user-avatar|drawer-user-copy/);
assert.match(app, /게스트 유저/);
assert.match(app, /drawer-theme-toggle/);
assert.match(app, /drawer-server-health/);
assert.doesNotMatch(navigationDrawerSource, /label: '모델 설정'/);
assert.doesNotMatch(app, /AdPlacement|data-ad-placement|AD SLOT|임시 광고|광고 영역|스폰서 구좌/);
assert.doesNotMatch(css, /ad-placement/);
assert.match(app, /if \(route\.page === 'home'\) return null/);
assert.doesNotMatch(app, /바로 이어가기/);
assert.match(app, /최근 대화방/);
assert.doesNotMatch(app, /최근 사용한 방|최근 대화한 방|가장 많이 사용한 캐릭터/);
assert.match(app, /자주 사용하는 캐릭터[\s\S]*자주 사용하는 세계관/);
assert.match(app, /room-participant-stack/);
assert.match(app, /room-participant-more/);
assert.match(css, /recommendMarqueeRight/);
assert.match(css, /\.recommend-scroll\.is-marquee/);
assert.match(css, /\.battle-balance-control input\[type="range"\][\s\S]*accent-color: var\(--primary\)/);
assert.match(app, /export type RuntimeSettingFieldsProps/);
assert.match(app, /export type RuntimeSettingsPanelProps/);
assert.match(app, /export type ChatSettingsBubbleProps/);
assert.match(app, /export type GenreModeFieldProps/);
assert.match(app, /export function GenreModeField\(\{ value, onChange \}: GenreModeFieldProps\)/);
assert.match(app, /export type CharacterCardPreviewModalProps/);
assert.match(app, /export function CharacterCardPreviewModal\(\{ character, onClose \}: CharacterCardPreviewModalProps\)/);
assert.match(app, /TraitSliders/);
assert.match(app, /export type TraitSlidersProps/);
assert.match(app, /export function TraitSliders\(\{ scores = \{\}, onChange, readOnly = false \}: TraitSlidersProps\)/);
assert.match(app, /readOnly\?: boolean/);
assert.match(app, /성향 슬라이더 design-system primitive marker/);
assert.match(app, /<Slider type="range" min="1" max="5"/);
assert.match(app, /disabled=\{readOnly\}/);
assert.doesNotMatch(app, /views\/Uiux/);
assert.match(app, /export function UiuxView/);
assert.match(app, /uiux design guide atomic sample marker/);
assert.match(app, /data-uiux-section=\{marker\}/);
assert.match(app, /token-palette/);
assert.match(app, /typography-scale/);
assert.match(app, /spacing-scale/);
assert.match(app, /button-states/);
assert.match(app, /card-patterns/);
assert.match(app, /chat-bubble-patterns/);
assert.match(app, /JSON 구조는 \*\*유지\*\*/);
assert.match(app, /thought: '구조는 단단하게, 화면은 자연스럽게.'/);
assert.doesNotMatch(app, /route\.page === 'uiux'|page: 'uiux'/);
assert.match(app, /tokens/);
assert.match(app, /atoms · molecules · organisms/);
assert.match(app, /views\/Statistics/);
assert.match(app, /통계 페이지 design-system primitive marker/);
assert.match(app, /conversationApi\.usageSummary/);
assert.match(app, /conversationApi\.usage\(conversationId, query\)/);
assert.match(app, /route\.page === 'statistics'/);
assert.match(app, /page: 'statistics'/);
assert.doesNotMatch(app, /ConversationDiagnostics/);
assert.doesNotMatch(app, /ContextPreviewPanel/);
assert.doesNotMatch(app, /UsageSummaryPanel/);
assert.doesNotMatch(app, /프롬프트 토큰 미리보기/);
assert.match(app, /export type AvatarPreviewModalProps/);
assert.match(app, /export function AvatarPreviewModal\(\{ preview, onClose \}: AvatarPreviewModalProps\)/);
assert.match(app, /아바타 미리보기 design-system modal card marker/);
assert.match(app, /캐릭터 카드 미리보기 design-system modal card marker/);
assert.match(app, /<Card className="avatar-preview-card"/);
assert.match(app, /<Card className="card-preview-modal"/);
assert.doesNotMatch(css, /\.section-title\b/);
assert.match(app, /<CardHeader className="flex flex-wrap items-baseline justify-between gap-2"/);

assert.match(app, /function parseRoute/);
assert.match(app, /window\.history\.pushState/);
assert.match(app, /drawerOpen = useUiStore/);
assert.match(app, /setDrawerOpen = useUiStore/);
assert.match(app, /export type UiStoreState/);
assert.match(app, /export const useUiStore = create<UiStoreState>/);
assert.match(app, /contextDrawerOpen = useUiStore/);
assert.match(app, /closeDrawers/);
assert.doesNotMatch(app, /menu-toggle/);
assert.match(app, /side-drawer/);
assert.match(app, /drawer-backdrop/);
assert.doesNotMatch(app, /<Nav route=\{route\} navigate=\{navigate\} \/>/);
assert.match(app, /route\.page === 'conversationDetail'/);
assert.match(app, /route\.page === 'characterDetail'/);
assert.match(app, /route\.page === 'characterNew'/);
assert.match(app, /\/participants/);
assert.match(app, /setParticipants/);
assert.match(app, /participantName/);
assert.match(app, /navigate\(`\/conversations\/\$\{conversation\.id\}`\)/);
assert.match(app, /navigate\(`\/characters\/\$\{c\.id\}`\)/);
assert.match(app, /async function sendConversationMessage/);
assert.doesNotMatch(app, /async function continueAutoTurns/);
assert.doesNotMatch(app, /const \[autoContinueTurns, setAutoContinueTurns\]/);
assert.doesNotMatch(app, /autoContinueTurns/);
assert.doesNotMatch(app, /setAutoContinueTurns/);
assert.doesNotMatch(app, /자동 턴/);
assert.doesNotMatch(app, /`자동 \$\{autoContinueTurns\}턴`/);
assert.match(app, /components\/atoms/);
assert.match(app, /label=\{t\('활성화'\)\}/);
assert.match(app, /chat-thread/);
assert.match(app, /MESSAGE_PAGE_TURNS = 10/);
assert.match(app, /recent_turns=\$\{MESSAGE_PAGE_TURNS\}/);
assert.match(app, /async function loadOlderMessages/);
assert.match(app, /conversationApi\.messages\(selectedConversationId, oldestPersisted\.id\)/);
assert.match(app, /skipNextAutoScrollRef/);
assert.match(app, /olderPagingReady/);
assert.match(app, /setOlderPagingReady\(false\)/);
assert.match(app, /setTimeout\(\(\) => setOlderPagingReady\(true\), 350\)/);
assert.match(app, /nextScrollModeRef/);
assert.match(app, /lastMessageTailRef/);
assert.match(app, /explicitMode === 'append'/);
assert.match(app, /explicitMode === 'preserve'/);
assert.match(app, /node\.scrollTop = node\.scrollHeight/);
assert.match(app, /node\.scrollTop = node\.scrollHeight - previousScrollHeight \+ previousScrollTop/);
assert.doesNotMatch(app, /older-messages-loader/);
assert.doesNotMatch(css, /\.older-messages-loader\s*\{/);
assert.match(app, /export type BubbleListProps/);
assert.match(app, /export function BubbleList\(\{ messages, characters, onAvatarPreview, bottomRef, threadRef, onLoadOlderMessages, hasOlderMessages = false, loadingOlderMessages = false, olderPagingReady = false, onRetryMessage, renderImages = true, onGenerateTts, onRegenerateMessage, onDeleteMessage, onUpdateMessage, busy = false, selectionMode = false/);
assert.match(app, /채팅 버블 design-system primitive marker/);
assert.match(app, /CommandBlockRenderer/);
assert.match(app, /hasCommandBlocks && <div className="mt-2\.5 grid gap-2 rounded-2xl border border-border bg-card/);
assert.match(app, /text-card-foreground/);
assert.match(app, /border-border bg-card/);
assert.doesNotMatch(commandBlockSource, /bg-warning\/10/);
assert.doesNotMatch(app, /command-visible-overlay|command-comments-block|command-checklist-block|command-timeline-block|command-vote-block|command-cards-block/);
assert.doesNotMatch(css, /\.command-visible-overlay|\.command-vote-bar|\.command-card-grid|\.bubble-command-block/);
assert.doesNotMatch(app, /broadcast-visible-overlay|broadcast-command-card|broadcast-scene-card|broadcastNotice|hasBroadcastOverlay/);
assert.match(app, /<Button[^>]+bubble-menu-button/s);
assert.match(app, /<Button[^>]+message-select-toggle/s);
assert.match(app, /if \(message\.speaker_type === 'system' \|\| message\.speaker_type === 'storytelling'\) return 'center'/);
assert.match(app, /스토리텔링/);
assert.match(app, /bubble .*storytelling/);
assert.match(app, /if \(message\.speaker_type === 'user'\) return 'right'/);
assert.match(app, /return 'left'/);
assert.doesNotMatch(app, /message\.speaker_type === 'user' && isObserverRoom/);
assert.match(app, /onRetryMessage=\{retryMessage\}/);
assert.match(app, /retryPayload/);
assert.match(app, /failed: true/);
assert.match(app, /aria-label=\{t\('마지막 입력 재요청'\)\}/);
assert.match(app, /async function retryMessage/);
assert.match(app, /async function deleteMessageBubble/);
assert.match(app, /async function deleteSelectedMessages/);
assert.match(app, /enterMessageSelectionMode/);
assert.match(app, /onPointerDown=\{\(\) => startLongPress\(message\)\}/);
assert.match(app, /message-selection-toolbar/);
assert.match(app, /jump-to-latest-button/);
assert.match(app, /scrollToLatest/);
assert.match(app, /\/messages\/bulk-delete/);
assert.match(app, /conversationApi\.deleteMessage/);
assert.match(app, /formatDangerConfirmation\('message', locale\)/);
assert.match(app, /danger-menu-item/);
assert.match(app, /async function submitConversationPayload/);
assert.doesNotMatch(app, /typingMessage/);
assert.match(app, /async function revealServerMessages/);
assert.match(app, /serverMessages\.slice\(1\)/);
assert.match(app, /const BUBBLE_REVEAL_DELAY_MS = 3000/);
assert.match(app, /await delay\(BUBBLE_REVEAL_DELAY_MS\)/);
assert.match(app, /const typingId = `typing_\$\{message\.id\}`/);
assert.match(app, /is_typing: true/);
assert.match(app, /current\.map\(\(item\) => item\.id === typingId \? message : item\)/);
assert.match(app, /대화 생성 중/);
assert.doesNotMatch(app, /bubble-dialogue/);
assert.equal(typeof packageJson.dependencies['react-markdown'], 'string');
assert.match(app, /export function BubbleRichText/);
assert.match(app, /allowedElements=\{BUBBLE_MARKDOWN_ELEMENTS\}/);
assert.match(app, /BUBBLE_MARKDOWN_ELEMENTS: string\[\] = \['p', 'strong', 'em', 'code', 'br'\]/);
assert.match(app, /skipHtml/);
assert.match(app, /unwrapDisallowed/);
assert.doesNotMatch(app, /rehypeRaw/);
assert.match(app, /data-semantic-part="action"/);
assert.match(app, /data-semantic-part="dialogue"/);
assert.match(app, /data-semantic-part="thought"/);
assert.match(app, /text-\[15px\]/);
assert.match(app, /border-l-2/);
assert.match(app, /bg-violet-500\/10/);
assert.doesNotMatch(app, />\(\{part\.text\}\)<\/div>/);
assert.match(app, /message\.action/);
assert.match(app, /message\.thought/);
assert.match(app, /function avatarUrlFor/);
assert.doesNotMatch(app, /function ParticipantMoodStrip/);
assert.match(app, /const \[avatarPreview, setAvatarPreview\]/);
assert.match(app, /function AvatarPreviewModal/);
assert.match(app, /avatar-character-info/);
assert.match(app, /<h3>\{t\('설명'\)\}<\/h3>/);
assert.match(app, /<h3>\{t\('페르소나'\)\}<\/h3>/);
assert.match(app, /character\.description \|\| t\('저장된 설명 없음'\)/);
assert.match(app, /character\.persona \|\| t\('저장된 페르소나 없음'\)/);
assert.match(app, /onClick=\{\(\) => onAvatarPreview\?\.\(\{ character, emotion: message\.emotion \|\| t\('아직 없음'\), src: avatarUrlFor\(character, theme\) \}\)\}/);
assert.match(app, /const \[battleControlDraft, setBattleControlDraft\]/);
assert.match(app, /battle_control: battleControlPayload/);
assert.match(app, /loadBattleState\(selectedConversationId\)/);
assert.match(app, /if \(room\.genre_mode === 'battle'\) await loadBattleState\(conversationId, room\)/);
assert.match(app, /else setBattleState\(null\)/);
assert.match(app, /battle-control-panel/);
assert.match(app, /battle-control-fab/);
assert.match(app, /battle-control-popover/);
assert.match(app, /battle-control-compact-summary/);
assert.match(app, /<Badge>\{battleControlSummary\}<\/Badge>/);
assert.match(app, /<Button type="button" variant="ghost" size="sm"/);
assert.match(app, /const \[battleControlOpen, setBattleControlOpen\] = useState\(false\)/);
assert.match(app, /aria-label=\{t\('배틀 컨트롤 열기'\)\}/);
assert.match(app, /배틀 컨트롤/);
assert.match(app, /배틀 시작/);
assert.match(app, /배틀 중/);
assert.match(app, /배틀 종료/);
assert.match(app, /우위 슬라이더/);
assert.match(app, /progress_balance/);
assert.match(app, /battle-balance-labels/);
assert.match(app, /favoredCharacterId = balance < 0\.45 \? active\.participant_a_id : balance > 0\.55 \? active\.participant_b_id : undefined/);
assert.match(app, /const advantage = favoredCharacterId \? Math\.max\(balance, 1 - balance\) : 0\.5/);
assert.match(app, /autoSelectBattleParticipants/);
assert.match(app, /battleParticipants\.length === 2/);
assert.match(app, /formatActiveMatch\(activeMatch\.participant_a_name, activeMatch\.participant_b_name, locale\)/);
assert.match(app, /종료 후 입력 모드는 일반으로 자동 전환됩니다/);
assert.match(app, /setBattleControlDraft\(\{ action: 'none', advantage: 0\.5, progress_balance: 0\.5, current_phase: 'opening' \}\)/);
assert.match(app, /battleFighters/);
assert.match(app, /participant_a_id/);
assert.match(app, /winner_id/);

assert.match(app, /battleControlDraft=\{battleControlDraft\}/);
assert.match(app, /setBattleControlDraft=\{setBattleControlDraft\}/);
assert.match(app, /onKeyDown=\{handleComposerKeyDown\}/);
assert.match(app, /event\.key === 'Enter' && \(event\.ctrlKey \|\| event\.metaKey\)/);
assert.match(app, /<Textarea[^>]+value=\{compose\}/s);
assert.match(app, /Ctrl\+Enter/);
assert.doesNotMatch(app, /Shift\+Enter/);
assert.doesNotMatch(app, /ParticipantMoodStrip participants=/);
assert.doesNotMatch(app, /participant-avatar/);
assert.doesNotMatch(app, /chat-avatar-button|chat-avatar/);
assert.match(app, /size-11 min-h-11 shrink-0 rounded-full/);
assert.doesNotMatch(app, /size-\[34px\] min-h-\[34px\]/);
assert.doesNotMatch(app, /emotion: \{message\.emotion\}/);
assert.doesNotMatch(app, /composer-hint/);
assert.doesNotMatch(app, /chat-tools-details/);
assert.match(app, /chat-header-button/);
assert.match(app, /chat-back-button/);
assert.match(app, /chat-context-button/);
assert.match(app, /aria-label=\{t\('대화 흐름 열기'\)\}/);
assert.match(app, /export type ConversationInfoDrawerProps/);
assert.match(app, /export function ConversationInfoDrawer\(/);
assert.match(app, /const \[activeDrawerTab, setActiveDrawerTab\] = useState<DrawerTab>/);
assert.match(app, /drawerTabs: Array<\[DrawerTab, string\]> = \[/);
assert.match(app, /\['manage', t\('관리'\)\]/);
assert.match(app, /\['state', t\('상태'\)\]/);
assert.doesNotMatch(app, /\['diagnostics', '진단'\]/);
assert.doesNotMatch(drawerSource, /diagnostics/);
assert.doesNotMatch(app, /\['relationships', '관계'\]/);
assert.match(app, /\['memory', t\('유저노트'\)\]/);
assert.match(app, /className="drawer-tab-bar"/);
assert.match(app, /className="drawer-tab-content"/);
assert.match(app, /role="tabpanel"/);
assert.match(app, /contextDrawerOpen/);
assert.match(app, /loadConversationContext/);
assert.match(app, /\/context/);
assert.doesNotMatch(app, /대화방 내 관계상태/);
assert.doesNotMatch(app, /캐릭터 설정의 고정 관계가 아니라/);
assert.doesNotMatch(app, /관계 팩트/);
assert.match(drawerSource, /relationshipArchetypeLabel/);
assert.match(drawerSource, /RELATIONSHIP_ARCHETYPE_PRESETS/);
assert.match(drawerSource, /공략맛 프로필/);
assert.match(drawerSource, /관계 진행 타입/);
assert.doesNotMatch(app, /state\.relationship_fact/);
assert.doesNotMatch(app, /state\.current_dynamic && <p><b>관계 팩트<\/b>/);
assert.doesNotMatch(app, /다음 질문과 진행 훅은 내부 처리용이라 숨깁니다/);
assert.doesNotMatch(app, /state\.unresolved_hooks/);
assert.doesNotMatch(app, /이어갈 훅 없음/);
assert.match(app, /compressionText/);
assert.match(app, /유저노트/);
assert.match(app, /commonMemories/);
assert.match(app, /<strong>\{t\('공통 유저노트'\)\}<\/strong>/);
assert.doesNotMatch(drawerSource, /모든 캐릭터가 아는 내용/);
assert.match(app, /저장된 공통 유저노트 없음/);
assert.match(app, /유저노트 추가/);
assert.doesNotMatch(app, /직접 입력 유저노트/);
assert.match(app, /memory-compose-card/);
assert.match(app, /onCreateUserMemory/);
assert.match(app, /onUpdateMemory/);
assert.match(app, /editingMemoryId/);
assert.match(app, /submitMemoryEdit/);
assert.match(app, /수정 저장/);
assert.match(app, /updateMemory: \(id: Id, memoryId: Id, payload: Payload\) => api\(`\/conversations\/\$\{id\}\/memories\/\$\{memoryId\}`/);
assert.match(app, /onDeleteMemory/);
assert.match(app, /\/memories/);
assert.match(app, /formatDangerConfirmation\('memory', locale\)/);
assert.doesNotMatch(app, /최근 흐름/);
assert.doesNotMatch(app, /recentFlow/);
assert.match(css, /\.shell:has\(\.chat-shell\)/);
assert.match(css, /height:\s*100dvh/);
assert.match(css, /\.chat-header/);
assert.match(css, /grid-template-columns:\s*44px minmax\(0, 1fr\) auto/);
assert.match(css, /\.chat-header-actions/);
assert.match(css, /\.chat-header-button/);
assert.match(css, /\.chat-context-button/);
assert.match(css, /\.context-drawer/);
assert.match(css, /\.context-drawer-backdrop/);
assert.match(css, /\.drawer-tab-bar/);
assert.match(css, /\.drawer-tab-content/);
assert.match(css, /overscroll-behavior:\s*contain/);
assert.match(css, /\.drawer-tab-panel/);
assert.match(css, /\.context-summary/);
assert.match(css, /\.memory-compose-card/);
assert.match(css, /\.memory-row/);
assert.match(app, /memory-content/);
assert.match(css, /\.memory-content\s*\{[^}]*white-space:\s*pre-wrap/s);
assert.match(css, /\.memory-content\s*\{[^}]*overflow-wrap:\s*anywhere/s);
assert.match(css, /\.score-grid/);
assert.match(css, /\.composer/);
assert.match(css, /grid-template-columns:\s*88px minmax\(0, 1fr\) 44px auto/);
assert.match(css, /\.composer > select, \.composer > button[^}]*height:\s*44px/s);
assert.match(css, /\.composer \.chat-settings-button/);
assert.match(css, /\.composer textarea[^}]*min-height:\s*48px/s);
assert.match(css, /max-height:\s*118px/);
assert.match(css, /\.composer > \.composer-expand-trigger/);
assert.match(app, /composerTextareaRef/);
assert.match(app, /setComposeExpanded/);
assert.match(app, /메시지 크게 쓰기/);
assert.match(css, /\.bubble\.left/);
assert.match(css, /\.bubble\.right/);
assert.match(css, /\.bubble\.center/);
assert.doesNotMatch(css, /\.participant-mood-strip/);
assert.doesNotMatch(css, /\.participant-avatar/);
assert.match(css, /\.chat-body-wrap/);
assert.match(css, /\.message-selection-toolbar/);
assert.match(css, /\.message-select-toggle/);
assert.match(css, /\.jump-to-latest-button/);
assert.doesNotMatch(app, /chat-message-row/);
assert.doesNotMatch(css, /\.chat-message-row\s*\{/);
assert.doesNotMatch(css, /\.chat-message-row\.right\s*\{/);
assert.doesNotMatch(css, /\.chat-message-row\.center\s*\{/);
assert.doesNotMatch(css, /\.chat-message-row\.left\s*\{/);
assert.doesNotMatch(css, /\.chat-message-row\.selecting\s*\{/);
assert.doesNotMatch(css, /\.chat-message-row\.selected \.bubble/);
assert.match(app, /side === 'right' \? 'justify-end' : ''/);
assert.match(app, /side === 'center' \? 'justify-center' : ''/);
assert.match(app, /selectionMode \? 'cursor-pointer' : ''/);
assert.doesNotMatch(app, /className="chat-avatar-button"|className="chat-avatar"/);
assert.doesNotMatch(css, /\.chat-avatar-button\s*\{|\.chat-avatar\s*\{/);
assert.match(app, /size-11 min-h-11 shrink-0 rounded-full/);
assert.doesNotMatch(app, /size-\[34px\] min-h-\[34px\]/);
assert.match(css, /\.avatar-modal/);
assert.match(css, /\.avatar-preview-image/);
assert.match(css, /\.avatar-character-info/);
assert.match(css, /white-space: pre-wrap/);
assert.match(css, /\.bubble\.storytelling/);
assert.match(app, /italic/);
assert.doesNotMatch(app, /className=\"bubble-action\"|className=\"bubble-thought\"|className=\"bubble-error\"|className=\"bubble-tts-row\"/);
assert.doesNotMatch(css, /\.bubble-action\s*\{|\.bubble-thought\s*\{|\.bubble-error\s*\{|\.bubble-tts-row\s*\{/);
assert.doesNotMatch(app, /className="retry-row"|className="retry-button"/);
assert.doesNotMatch(css, /\.retry-row\s*\{|\.retry-button\s*\{/);
assert.doesNotMatch(app, /className="typing-skeleton"/);
assert.doesNotMatch(css, /\.typing-skeleton\s*\{|\.typing-skeleton span/);
assert.match(css, /@keyframes typingPulse/);
assert.match(css, /font-size:\s*(0\.8|\.8|80%|12px)/);
assert.doesNotMatch(css, /\.auto-turn-controls/);
assert.match(css, /\.chat-shell/);
assert.doesNotMatch(css, /\.composer-hint/);
assert.match(app, /const isChatRoute = route\.page === 'conversationDetail'/);
assert.match(app, /!isChatRoute && <header className="app-bar[^"]*bg-card/);
assert.match(appShellSource, /<h1[^>]*text-\[16px\]/);
assert.match(css, /\.app-title h1 \{[^}]*font-size:\s*16px;[^}]*line-height:\s*1\.2/s);
assert.match(homeView, /className="room-thumbnail-default"[^>]*data-default-thumbnail/);
assert.match(css, /\.room-recommend-card \{[^}]*grid-template-rows:\s*132px minmax\(54px, auto\)/s);
assert.match(css, /\.room-thumbnail-default > img \{[^}]*width:\s*64px !important;[^}]*height:\s*64px !important;[^}]*object-fit:\s*contain !important/s);
assert.doesNotMatch(homeView, /object-contain object-center bg-surface-muted p-3/);
assert.doesNotMatch(appShellSource, /bg-card\/85/);
assert.doesNotMatch(css, /\.menu-toggle|button\.ghost|button\.danger|\.compact-button/);
assert.match(css, /\.side-drawer/);
assert.match(css, /\.drawer-backdrop/);
assert.doesNotMatch(css, /\.top-nav \{/);
assert.match(app, /대화방 제목/);
assert.match(app, /selectedWorldSettingId/);
assert.match(app, /world_setting_id: selectedWorldSettingId/);
assert.match(app, /normalizeGenreMode\(selectedWorld\?\.genre_mode \|\| genreMode\)/);
assert.match(app, /genreModeLabel\(c\.genre_mode\)/);
assert.doesNotMatch(conversationsView, /function conversationGenreIcon\(/);
assert.doesNotMatch(conversationsView, /conversation-genre-icon/);
assert.doesNotMatch(conversationsView, /장르 아이콘/);
assert.match(conversationsView, /function ConversationThumbnail\(/);
assert.doesNotMatch(app, /conversation-fallback-thumbnail|brand-fallback-thumbnail/);
assert.doesNotMatch(css, /\.conversation-fallback-thumbnail|\.brand-fallback-thumbnail/);
assert.match(app, /data-resource-card=\{variant\}/);
assert.match(app, /data-resource-actions/);
assert.match(conversationsView, /ResourceCardAction label=\{formatNamedAction\(c\.title \|\| t\('대화방'\), 'edit', locale\)\}/);
assert.match(conversationsView, /ResourceCardAction label=\{formatNamedAction\(c\.title \|\| t\('대화방'\), 'delete', locale\)\} variant="destructive"/);
assert.match(buttonPrimitive, /sm: 'min-h-9 px-3\.5 py-2 text-xs'/);
assert.doesNotMatch(css, /^button \{[^\n]*padding: 0/m);
assert.doesNotMatch(css, /^button \{[^\n]*min-height: 40px/m);
assert.doesNotMatch(css, /^button \{[^\n]*font: inherit/m);
assert.doesNotMatch(conversationsView, /상세 페이지에서 대화를 이어갈 수 있습니다/);
assert.doesNotMatch(conversationsView, /\{c\.mode\}/);
assert.doesNotMatch(conversationsView, /<small>\{c\.id\}/);
assert.doesNotMatch(conversationsView, /\{c\.title \|\| c\.id\}/);
assert.doesNotMatch(conversationsView, /auto'\s*:\s*'manual/);
assert.doesNotMatch(conversationsView, /character_character|user_character/);
assert.match(genreSource, /label: '배틀'/);
assert.match(app, /WorldSettingsListView/);
assert.match(app, /WorldSettingsDetailView/);
assert.doesNotMatch(css, /\.field\b|\.field-hint|^input, textarea, select|input:focus, textarea:focus, select:focus/m);
assert.match(app, /conversationTitle/);
assert.match(app, /세계관 선택은 필수입니다/);
assert.match(app, /세계관을 먼저 선택해야 합니다/);
assert.doesNotMatch(app, /world_setting_id: selectedWorldSettingId \|\| null/);
assert.doesNotMatch(app, /relationship_archetype: scene\.relationship_archetype/);
assert.doesNotMatch(app, /world_seed: roomEditDraft\.seed/);
assert.doesNotMatch(app, /opening_scene: roomEditDraft\.opening_scene/);
assert.doesNotMatch(app, /compression_focus: roomEditDraft\.compression_focus/);
assert.doesNotMatch(app, /방 썸네일 URL/);
assert.doesNotMatch(app, /세계관 프리셋 불러오기/);
assert.doesNotMatch(app, /룸 템플릿 불러오기/);
assert.doesNotMatch(app, /roomMode/);
assert.match(app, /user_character/);
assert.match(app, /character_character/);
assert.doesNotMatch(app, /나 vs 캐릭터 1:1/);
assert.match(app, /userDescription/);
assert.match(app, /유저페르소나/);
assert.match(app, /USER_SETTING_PRESETS/);
assert.match(app, /user_setting/);
assert.match(app, /user_description/);
assert.match(app, /주요 압축포인트/);
assert.match(app, /compression_focus/);
assert.match(app, /지금 압축/);
assert.match(app, /async function compressConversationNow/);
assert.match(app, /\/compress-now/);
assert.doesNotMatch(app, /지금: 채팅/);
assert.match(app, /PRESET_TYPE_LABELS/);
assert.doesNotMatch(app, /<option value="compression_focus">주요 압축포인트<\/option>/);
assert.doesNotMatch(app, /나에 대한 설명/);
assert.match(app, /세계관 관리/);
assert.match(app, /worldSettings/);
assert.match(app, /첫 상황/);
assert.match(app, /첫 대사/);
assert.match(app, /방 대화 톤/);
assert.match(app, /관계 진행 타입/);
assert.match(app, /공략맛 프로필/);
assert.match(app, /집착 높음 · 신뢰 낮음/);
assert.match(app, /츤데레 · 숨은 호감/);
assert.match(app, /relationship_archetype/);
assert.match(app, /tone_preset/);
assert.match(app, /빠른 티키타카/);
assert.match(app, /느린 감정선/);
assert.match(app, /opening_scene/);
assert.match(app, /opening_line/);
assert.doesNotMatch(app, /sceneState\.opening_scene/);
assert.doesNotMatch(app, /sceneState\.opening_line/);
assert.doesNotMatch(app, /world_seed: scene\.seed/);
assert.doesNotMatch(app, /opening_scene: scene\.opening_scene/);
assert.doesNotMatch(app, /opening_line: scene\.opening_line/);
assert.doesNotMatch(app, /tone_preset: scene\.tone_preset/);
assert.doesNotMatch(app, /relationship_archetype: scene\.relationship_archetype/);
assert.doesNotMatch(app, /첫 장면은 다음 phase의 첫 상황 필드로 분리/);
assert.doesNotMatch(app, /방의 세계관, 관계 구도, 시작 상황/);
assert.doesNotMatch(app, /대화 컨셉/);
assert.match(app, /multiCharacterIds/);
assert.match(app, /addMultiCharacterSlot/);
assert.match(app, /removeMultiCharacterSlot/);
assert.match(app, /\+ 캐릭터 추가/);
assert.match(app, /CAST_ROLE_PRESETS/);
assert.match(genreSource, /export const CAST_ROLE_PRESETS/);
assert.match(app, /캐릭터 역할/);
assert.doesNotMatch(app, /역할 \/ 발화 포지션/);
assert.match(app, /메인 캐릭터/);
assert.match(app, /라이벌·견제자/);
assert.match(app, /말하지 않음/);
assert.match(app, /updateMultiCharacterRole/);
assert.match(app, /multiCharacterRoles/);
assert.match(app, /role: multiCharacterRoles\[slot\.index\] \|\| null/);
assert.match(app, /participants: normalizedParticipants/);
assert.match(app, /role: participant\.role \|\| ''/);
assert.match(app, /updateParticipantRole/);
assert.match(app, /conversationApi\.participants\(conversationId\)/);
assert.match(app, /sceneDraftFromContext\(room, context, roomParticipants\)/);
assert.match(app, /participants: roomParticipants\.map/);
assert.doesNotMatch(app, /setMultiCharacterRoles\(ids\.map\(\(_id, index\) => roles\[index\] \?\? defaultCastRoleForSlot\(index\)\)\)/);
assert.doesNotMatch(app, /participant_roles/);
assert.doesNotMatch(app, /다중 캐릭터방은 최소 2명/);
assert.match(app, /참여 캐릭터를 1명 이상 선택해야 합니다/);
assert.match(app, /새 대화방/);
assert.match(app, /startConversationRoom/);
assert.match(generationJobEventsSource, /new URL\(relativePath, browserOrigin\)/);
assert.match(generationJobEventsSource, /apiBase = API_BASE/);
assert.match(generationJobEventsSource, /browserOrigin = window\.location\.origin/);
assert.match(generationJobEventsSource, /new EventSource\(url\.toString\(\)\)/);
assert.match(generationJobEventsSource, /generation-jobs\/\$\{encodeURIComponent\(jobId\)\}\/events/);
assert.match(generationJobEventsSource, /after_event_id/);
assert.match(generationJobEventsSource, /Lifecycle SSE repeatedly disconnected/);
assert.match(appRootSource, /async function waitForGenerationJob[\s\S]*let subscription:[^\n]+ = null;\s*try \{\s*subscription = subscribeGenerationJobLifecycle/);
assert.doesNotMatch(appRootSource, /const subscription = subscribeGenerationJobLifecycle\([\s\S]*?\);\s*activeGenerationSubscriptionRef\.current = subscription;\s*try \{/);
assert.match(appRootSource, /catch \(error\) \{[\s\S]*return await pollGenerationJob\(conversationId, jobId\)/);
assert.match(app, /activeGenerationSubscriptionRef\.current\?\.close\(\)/);
assert.doesNotMatch(app, /auto-turns\/stream/);
assert.doesNotMatch(app, /한 번의 모델 호출로 여러 캐릭터 버블/);
assert.doesNotMatch(app, /빠른 입력 A/);
assert.doesNotMatch(app, /빠른 입력 B/);
assert.doesNotMatch(app, /quickA/);
assert.doesNotMatch(app, /quickB/);
assert.match(app, /캐릭터 목록/);
assert.doesNotMatch(app, /상세 설정/);
assert.match(app, /대화방 목록/);
assert.match(app, /export type CharacterFormProps/);
assert.match(app, /export function CharacterForm\(/);
assert.match(app, /export type CharacterAssetsPanelProps/);
assert.match(app, /export function CharacterAssetsPanel\(/);
assert.match(app, /캐릭터 폼 design-system primitive marker/);
assert.match(app, /캐릭터 에셋 패널 design-system primitive marker/);
assert.match(app, /캐릭터 에셋 컨트롤 flat form section/);
assert.doesNotMatch(app, /<CardHeader className="flex items-center justify-between gap-3/);
assert.match(app, /<Switch[^>]+label=\{t\('활성화'\)\}/s);
assert.match(app, /<Switch[^>]+label=\{t\('기본 프사'\)\}/s);
assert.doesNotMatch(app, /className="check-row"/);
assert.match(app, /views\/CharacterDetail/);
assert.match(app, /export type CharacterDetailViewProps/);
assert.match(app, /export function CharacterDetailView\(/);
assert.match(app, /캐릭터 상세 design-system primitive marker/);
assert.doesNotMatch(app, /<CardTitle>\{route\.page === 'characterNew'/);
assert.match(app, /views\/CharacterAssets/);
assert.match(app, /export type CharacterAssetsViewProps/);
assert.match(app, /export function CharacterAssetsView\(/);
assert.match(app, /에셋 갤러리 design-system primitive marker/);
assert.match(app, /useCharacterMutations/);
assert.match(app, /characterApi\.createAsset/);
assert.match(app, /characterApi\.setDefaultAsset/);
assert.match(app, /에셋 갤러리/);
assert.match(app, /message\.assets && message\.assets\.length > 0/);
assert.match(app, /bubble-assets/);
assert.match(app, /variant="mediaSquare"/);
assert.match(app, /data-image-shape="square"/);
assert.match(app, /assetUrlFor/);
assert.doesNotMatch(app, /asset-gallery-page|photo-asset-thumb|asset-modal-card|gallery-toolbar|asset-create-grid/);
assert.doesNotMatch(css, /\.asset-gallery-page|\.photo-asset-thumb|\.asset-modal-card|\.gallery-toolbar|\.asset-create-grid/);
assert.match(css, /\.bubble-asset-image/);
assert.match(css, /\.chat-image-frame \{[^}]*aspect-ratio: 1;/);
assert.match(css, /\.bubble-assets \{[^}]*width: min\(100%, 22rem\)/);
assert.match(css, /\.bubble-asset-image \{[^}]*height: 100%;[^}]*max-height: none;[^}]*aspect-ratio: 1;[^}]*object-fit: contain;/);
assert.match(css, /@media \(min-width: 600px\) and \(max-width: 1039px\)[\s\S]*\.bubble \{ max-width: min\(72%, 28rem\); \}/);
assert.doesNotMatch(css, /\.bubble-asset-image \{[^}]*max-height: 280px/);
assert.match(css, /\.chat-image-frame \*,[\s\S]*border-radius: 0 !important/);

assert.match(app, /const TRAIT_DEFINITIONS/);
assert.match(app, /trait_scores/);
assert.match(app, /function TraitSliders/);
assert.match(app, /type="range"/);
assert.match(app, /자신감/);
assert.match(app, /에로스/);
assert.match(app, /질투심/);
assert.doesNotMatch(css, /\.trait-grid|\.trait-row|\.trait-copy|\.trait-score|\.multi-character-picker|\.multi-character-row|\.tts-card/);
assert.doesNotMatch(css, /\.runtime-settings-card|\.runtime-setting-grid|\.chat-settings-head/);

assert.match(app, /async function deleteConversation/);
assert.match(app, /method: 'DELETE'/);
assert.match(app, /삭제/);
assert.match(app, /route\.page === 'conversationEdit'/);
assert.match(app, /page: 'conversationEdit'/);
assert.match(app, /navigate\(`\/conversations\/\$\{c\.id\}\/edit`\)/);
assert.match(app, /async function saveConversationRoomEdit/);
assert.match(app, /roomEditDraft/);
assert.doesNotMatch(app, /applyRoomEditPreset\('compression_focus'/);
assert.match(app, /extractUserDescriptionFromScene/);
assert.match(app, /대화방 수정/);
assert.match(app, /character-card-avatar/);
assert.match(app, /캐릭터 목록/);
assert.match(app, /src=\{avatarUrlFor\(c, theme\)\}/);
assert.match(css, /\.character-card-avatar/);
assert.match(css, /\.conversation-card-actions/);
assert.match(css, /\.list-card-content/);

assert.doesNotMatch(app, /createTypingMessage/);
assert.doesNotMatch(app, /source\.addEventListener\('typing'/);
assert.doesNotMatch(app, /replaceTypingWithMessage/);
assert.doesNotMatch(app, /typing_\$\{message\.speaker_id\}/);

assert.match(app, /useRef/);
assert.match(app, /const chatEndRef = useRef(?:<[^>]+>)?\(null\)/);
assert.match(app, /chatEndRef\.current\?\.scrollIntoView/);
assert.match(app, /\[messages, selectedConversationId, route\.page, olderPagingReady\]/);
assert.match(app, /<div ref=\{bottomRef\} className="w-full flex-\[0_0_1px\]"/);
assert.doesNotMatch(app, /\}, \[route, characters\.length\]\)/);
assert.doesNotMatch(app, /chat-bottom-sentinel/);
assert.doesNotMatch(css, /\.chat-bottom-sentinel\s*\{/);

assert.doesNotMatch(app, /const MIN_TYPING_RENDER_MS = 2000/);
assert.doesNotMatch(app, /typingStartedAtRef/);
assert.doesNotMatch(app, /Date\.now\(\) - startedAt/);
assert.doesNotMatch(app, /Math\.max\(0, MIN_TYPING_RENDER_MS - elapsed\)/);
assert.match(app, /async function delay\(ms\)/);

assert.match(app, /const SYSTEM_ID = 'system'/);
assert.match(app, /presets/);
assert.match(app, /route\.page === 'presetNew'/);
assert.match(app, /route\.page === 'presetDetail'/);
assert.doesNotMatch(app, /lexicon(?:New|Detail|Entries|Draft|Query|Page|Usage)?|systemPrompts|systemPrompt(?:New|Detail|Draft|Query|Page)?|system-prompts/);
assert.match(app, /page: 'characterAssets'/);
assert.match(app, /image-assets-tab/);
assert.match(app, /<CharacterAssetsPanel character=\{draft\}/);
assert.match(app, /assets=\{characterAssets\}/);
assert.match(app, /\+ 에셋 추가/);
assert.match(app, /grid-cols-2 gap-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5/);
assert.match(app, /!rounded-none/);
assert.match(app, /setSelectedAsset\(asset\)/);
assert.match(app, /role="dialog"/);
assert.match(app, /에셋 상세 닫기/);
assert.doesNotMatch(css, /\.photo-gallery-grid|\.photo-asset-thumb|\.asset-modal/);
assert.match(app, /const \[battleState, setBattleState\]/);
assert.doesNotMatch(app, /async function loadConversationUsage/);
assert.doesNotMatch(app, /async function loadContextPreview/);
assert.match(app, /async function loadBattleState/);
assert.doesNotMatch(app, /async function loadConversationDiagnostics/);
assert.match(app, /battleState: \(id: Id\) => api\(`\/conversations\/\$\{id\}\/battle-state`\)/);
assert.match(app, /export type BattleState/);
assert.match(app, /battleState\?: BattleState \| null/);
assert.match(app, /conversation\?\.genre_mode === 'battle'/);
assert.match(app, /\['battle', t\('배틀'\)\]/);
assert.match(app, /aria-label=\{t\('배틀 기록'\)\}/);
assert.match(app, /현재 진행중인 배틀 없음/);
assert.match(app, /recent_matches/);
assert.match(app, /standings/);
assert.match(app, /function UsageBuckets/);
assert.match(app, /groupUsageBuckets/);
assert.doesNotMatch(app, /stats-provider-card|stats-provider-summary-main|stats-provider-summary-total|stats-filter-grid|stats-room-select|stats-purpose-row/);
assert.doesNotMatch(css, /\.stats-provider-card|\.stats-provider-summary-main|\.stats-provider-summary-total|\.stats-filter-grid|\.stats-room-select|\.stats-purpose-row/);
assert.match(app, /chat_generation/);
assert.match(app, /conversation_compression/);
assert.doesNotMatch(app, /function ContextPreviewPanel/);
assert.doesNotMatch(app, /프롬프트 토큰 미리보기/);
assert.doesNotMatch(app, /실제로 들어가는 프롬프트 섹션만 표시/);
assert.doesNotMatch(app, /section\.included !== false/);
assert.doesNotMatch(app, /제외됨 ·/);
assert.doesNotMatch(app, /대략 토큰/);
assert.doesNotMatch(app, /recent_message_count/);
assert.match(app, /function CharacterCardPreviewModal/);
assert.match(app, /카드 미리보기/);
assert.match(app, /card-preview-avatar/);
assert.match(app, /src=\{avatarUrlFor\(character, theme\)\}/);
assert.doesNotMatch(app, /persona_background/);
assert.doesNotMatch(app, /appearance_reference/);
assert.doesNotMatch(app, /behavior_style<\/h3>/);
assert.doesNotMatch(app, /speech_examples/);
assert.doesNotMatch(app, /trait_scores<\/h3>/);
assert.match(app, /<h3>\{t\('목록 설명'\)\}<\/h3>/);
assert.match(app, /<h3>\{t\('페르소나'\)\}<\/h3>/);
assert.match(app, /<h3>\{t\('외형 참조'\)\}<\/h3>/);
assert.match(app, /<h3>\{t\('행동 스타일'\)\}<\/h3>/);
assert.match(app, /<h3>\{t\('말투 예시'\)\}<\/h3>/);
assert.match(app, /<TraitSliders scores=\{character\.trait_scores\} readOnly \/>/);
assert.match(app, /aria-label=\{t\('카드 미리보기 닫기'\)\}/);
assert.match(app, /\['basic', t\('기본'\)\], \['prompt', t\('프롬프트'\)\], \['traits', t\('성향'\)\], \['tts', t\('TTS'\)\], \['images', t\('이미지'\)\]/);
assert.doesNotMatch(app, /운영 바로가기/);
assert.doesNotMatch(app, /비용 점검/);
assert.doesNotMatch(app, /컨텍스트 품질 체크리스트/);
assert.match(app, /bubble-action-menu/);
assert.match(app, /복사/);
assert.match(app, /이후 재생성/);
assert.match(app, /async function regenerateFromMessage/);
assert.match(app, /\/regenerate/);
assert.doesNotMatch(css, /\.diagnostic-stat-grid|\.diagnostics-panel|\.context-preview-card|\.ops-console|\.ops-card/);
assert.doesNotMatch(css, /\.image-toggle-card|\.image-toggle-copy|\.image-toggle-switch|\.chat-settings-close/);
assert.doesNotMatch(css, /\.context-chip-list|\.participant-chip|\.chip-remove|\.invite-icon|\.avatar-preview-caption/);
assert.match(css, /\.bubble-action-menu/);
assert.match(css, /\.card-preview-modal/);
assert.match(css, /\.card-preview-hero/);
assert.match(css, /\.card-preview-avatar/);
assert.doesNotMatch(css, /\.ops-link-grid/);
assert.match(app, /export type PresetFormProps/);
assert.match(app, /export function PresetForm\(\{ draft, setDraft, onSave, onDelete, saving, isNew \}: PresetFormProps\)/);
assert.doesNotMatch(app, /export type RoomTemplateBuilderProps/);
assert.doesNotMatch(app, /JSON 직접 입력 대신 폼으로 저장합니다/);
assert.match(app, /TextareaWithExpand/);
assert.match(css, /\.text-editor-modal/);
assert.match(css, /\.expandable-textarea-wrap/);
assert.match(app, /function Pager/);
assert.match(css, /\.category-tabs/);
assert.match(app, /프리셋 검색/);
assert.match(app, /navigate\('\/presets\/new'\)/);
assert.match(app, /navigate\(`\/presets\/\$\{preset\.id\}`\)/);
assert.match(app, /프리셋/);
assert.match(app, /page: 'settings'/);
assert.match(app, /path: '\/settings'/);
assert.doesNotMatch(app, /go\('\/lexicon'\)/);
assert.doesNotMatch(app, /go\('\/presets'\)/);
assert.doesNotMatch(app, /go\('\/system-prompts'\)/);
assert.match(app, /route\.page === 'settings'/);
assert.match(app, /기본 채팅 설정/);
assert.doesNotMatch(app, /<Field label="기본 모델">/);
assert.match(app, /response_length_preset/);
assert.match(app, /대화 길이/);
assert.doesNotMatch(app, /사진 표기/);
assert.match(app, /useUiStore\(\(state\) => state\.renderChatImages\)/);
assert.match(app, /useUiStore\(\(state\) => state\.setRenderChatImages\)/);
assert.doesNotMatch(app, /const \[renderChatImages, setRenderChatImages\] = useState\(true\)/);
assert.match(uiStoreSource, /import \{ createJSONStorage, persist \} from 'zustand\/middleware'/);
assert.match(uiStoreSource, /renderChatImages: boolean/);
assert.match(uiStoreSource, /setRenderChatImages: \(renderChatImages: boolean\) => void/);
assert.match(uiStoreSource, /persist<UiStoreState, \[\], \[\], PersistedUiStoreState>/);
assert.match(uiStoreSource, /name: 'character-runtime-ui'/);
assert.match(uiStoreSource, /createJSONStorage\(\(\) => localStorage\)/);
assert.match(uiStoreSource, /partialize: \(state\) => \(\{ renderChatImages: state\.renderChatImages \}\)/);
assert.match(app, /renderImages && message\.assets && message\.assets\.length > 0/);
assert.match(app, /행동스타일/);
assert.match(app, /behavior_style/);
assert.doesNotMatch(app, /scene_relevance_gate/);
assert.match(app, /외형 참조/);
assert.match(app, /appearance/);
assert.match(app, /low-priority 참조/);
assert.match(app, /말투예시/);
assert.doesNotMatch(app, /<Field label="말투">/);
assert.match(app, /톤앤매너/);
assert.match(app, /말버릇과 자주 쓰는 표현/);
assert.match(app, /감정별 말투 변화/);
assert.match(app, /호칭 변화까지 한 칸에 적어/);
assert.match(app, /그대로 복붙할 대사집이 아니라/);
assert.match(app, /applyPreset/);
assert.match(app, /onAvatarUpload/);
assert.match(app, /async function uploadAvatar/);
assert.match(app, /\/uploads\/avatars/);
assert.match(app, /type="file"/);
assert.match(app, /accept="image\/png,image\/jpeg,image\/webp,image\/gif"/);
assert.match(app, /아바타 파일 업로드/);
assert.match(app, /아바타 URL/);
assert.match(app, /avatar-upload-preview/);
assert.match(app, /const isFormData/);
assert.match(app, /data instanceof FormData/);
assert.match(app, /axios\.create/);
assert.match(app, /http\.interceptors\.request\.use/);
assert.match(app, /http\.interceptors\.response\.use/);
assert.match(css, /\.avatar-upload-row/);
assert.match(css, /\.avatar-upload-preview/);
assert.match(app, /function parseInputMarkup/);
assert.match(app, /isSingleAsteriskMarker/);
assert.doesNotMatch(app, /text\.startsWith\('\.\.\.'/);
assert.match(app, /placeholder=\{t\('\*액션묘사\* 대사'\)\}/);
assert.match(app, /const parsed = parseInputMarkup\(compose\.trim\(\)\)/);
assert.match(app, /render_parts: parsed\.parts/);
assert.match(app, /normalizedRenderPartsFor/);
assert.match(app, /hasRenderParts && renderParts\.map/);
assert.match(app, /\*액션묘사\* 대사/);
assert.match(app, /export function linesToArray\(value: unknown\): string\[\]/);
assert.match(app, /function cleanRuleLines/);
assert.doesNotMatch(app, /split\('\\n'\)\.map\(\(line\) => line\.trim\(\)\)\.filter\(Boolean\)/);
assert.match(app, /시스템/);
assert.match(app, /speaker_type: selected === SYSTEM_ID \? 'system'/);
assert.match(app, /message\.speaker_type === 'system'/);
assert.match(css, /\.bubble\.system/);
assert.match(app, /async function renameConversation/);
assert.match(app, /method: 'PATCH'/);
assert.match(app, /대화방명 편집/);
assert.match(app, /async function inviteCharacterToConversation/);
assert.match(app, /async function removeCharacterFromConversation/);
assert.match(app, /onRemoveCharacter=\{removeCharacterFromConversation\}/);
assert.match(app, /participants\/character\/\$\{characterId\}/);
assert.match(app, /title=\{t\('내보내기'\)\}/);
assert.match(app, />×<\/Button>/);
assert.doesNotMatch(app, /roomParticipants\.map\(\(p\) => participantName\(p\.id\)\)\.join/);
assert.match(app, /초대할 캐릭터 선택/);
assert.doesNotMatch(app, /자동으로 1:N 방처럼 동작|<p className="context-muted"><\/p>/);
assert.match(app, /method: 'DELETE'/);
assert.match(app, /function confirmDanger/);
assert.match(app, /sweetalert2/);
assert.match(app, /sweetalert2-react-content/);
assert.match(app, /Alert\.fire/);
assert.doesNotMatch(app, /window\.confirm/);
assert.match(css, /danger-confirm-popup/);
assert.match(app, /formatDangerConfirmation\('character', locale, draft\.name \|\| routeId\)/);
assert.match(app, /formatDangerConfirmation\('conversation', locale, room\?\.title \|\| conversationId\)/);
assert.match(app, /formatDangerConfirmation\('asset', locale\)/);
assert.match(app, /formatDangerConfirmation\('preset', locale\)/);
assert.doesNotMatch(app, /이 시스템 프롬프트를 삭제하시겠습니까/);
assert.doesNotMatch(css, /\.button-row\b/);
assert.doesNotMatch(app, /route\.page === 'relationshipMap'|route\.page === 'dataCleanup'/);
assert.doesNotMatch(app, /\/relationship-map|\/data-cleanup\/summary/);
assert.doesNotMatch(app, /read-only 후보|데이터 정리 카테고리|관계선 프리뷰/);
assert.match(css, /\.drawer-edit-row/);
assert.match(css, /\.drawer-invite-row/);

console.log('frontend contract ok');
